version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: appuserpassword
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  ServiceRegistry:
    image: serviceregistry:latest
    build:
      context: ./ServiceRegistry
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://ServiceRegistry:8761/eureka/
      SPRING_APPLICATION_NAME: ServiceRegistry
    networks:
      - app-network
    healthcheck:
      test: curl -fs http://localhost:8761/actuator/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s


  AuthManagerMicroservice:
    image: authmanagermicroservice:latest
    build:
      context: ./AuthManagerMicroservice
      dockerfile: Dockerfile
    ports:
      - "8183:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/appdb?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: appuser
      SPRING_DATASOURCE_PASSWORD: appuserpassword
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://ServiceRegistry:8761/eureka/
      SPRING_APPLICATION_NAME: AUTHMANAGERMICROSERVICE
      ADMIN_EMAIL: admin
      ADMIN_PASSWORD: admin@123secure
    depends_on:
      mysql:
        condition: service_healthy
      ServiceRegistry:
        condition: service_healthy
    networks:
      - app-network

  CartManagement:
    image: cart-management:latest
    build:
      context: ./CartManagement
      dockerfile: Dockerfile
    ports:
      - "8184:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/appdb?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: appuser
      SPRING_DATASOURCE_PASSWORD: appuserpassword
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://ServiceRegistry:8761/eureka/
      SPRING_APPLICATION_NAME: CART-MANAGEMENT
    depends_on:
      mysql:
        condition: service_healthy
      ServiceRegistry:
        condition: service_healthy
    networks:
      - app-network

  OrderManagement:
    image: order-management:latest
    build:
      context: ./OrderManagement
      dockerfile: Dockerfile
    ports:
      - "8188:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/appdb?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: appuser
      SPRING_DATASOURCE_PASSWORD: appuserpassword
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://ServiceRegistry:8761/eureka/
      SPRING_APPLICATION_NAME: ORDER-MANAGEMENT
    depends_on:
      mysql:
        condition: service_healthy
      ServiceRegistry:
        condition: service_healthy
    networks:
      - app-network

  ProductMicroservice:
    image: product-microservice:latest
    build:
      context: ./ProductMicroservice
      dockerfile: Dockerfile
    ports:
      - "8185:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/appdb?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: appuser
      SPRING_DATASOURCE_PASSWORD: appuserpassword
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://ServiceRegistry:8761/eureka/
      SPRING_APPLICATION_NAME: PRODUCT-MICROSERVICE
    depends_on:
      mysql:
        condition: service_healthy
      ServiceRegistry:
        condition: service_healthy
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge